name: CI/CD Dev

on:
  push:
    branches:
      - dev
  # workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: lekhacthanhtung/sui-faucet-service:latest
          labels: lekhacthanhtung/sui-faucet-service:latest
          # tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}

  ec2_deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SSH_HOST: ${{ secrets.EC2_HOST }}
          SSH_USER: ${{ secrets.EC2_USER }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
          chmod 700 ~/.ssh/private.key

      - name: Deploy to EC2
        env:
          SSH_HOST: ${{ secrets.EC2_HOST }}
          SSH_USER: ${{ secrets.EC2_USER }}
          
                
          MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}   
          MONGODB_DATABASE_NAME: ${{ secrets.MONGODB_DATABASE_NAME }}       
          
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ vars.REDIS_PORT }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_USERNAME: ${{ secrets.REDIS_USERNAME }}

          AMQP_URL: ${{ secrets.AMQP_URL }}

          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/private.key ${SSH_USER}@${SSH_HOST} "
            docker rm -f sui-faucet-service || true
            docker rmi lekhacthanhtung/sui-faucet-service:latest || true
            docker run -it -d \
            --name sui-faucet-service \
            -e VIRTUAL_HOST=\"dev-avail-racetrack.weminal.xyz\" \
            -e VIRTUAL_PORT=8081 \
            -e LETSENCRYPT_HOST=\"dev-avail-racetrack.weminal.xyz\" \
            -e LETSENCRYPT_EMAIL=\"weminal@gmail.com\" \
            -e NODE_ENV=\"dev\" \
            -e SECRET_KEY='${SECRET_KEY}' \
            -e MONGODB_CONNECTION_STRING='${MONGODB_CONNECTION_STRING}' \
            -e MONGODB_DATABASE_NAME='${MONGODB_DATABASE_NAME}' \
            -e HTTP_PORT=\"8081\" \
            -e REDIS_HOST='${REDIS_HOST}' \
            -e REDIS_PORT='${REDIS_PORT}' \
            -e REDIS_PASSWORD='${REDIS_PASSWORD}' \            
            -e REDIS_USERNAME='${REDIS_USERNAME}' \
            -e AMQP_URL='${AMQP_URL}' \
            lekhacthanhtung/sui-faucet-service
          "